version: '3.8'
services:
  memegen:
    build: 
      context: .
      dockerfile: Dockerfile.md
    ports:
      - "3000:80"
    environment:
      - API_KEY=${API_KEY}
      - ACCESS_CODE=${ACCESS_CODE}
